### ISSUE TITLE
Error running testAgent

### ISSUE THREAD

**Issue by RozenAstrayChen** [rubenrtorrado/GVGAI_GYM#12]
Hello, when I try to run ```GVGAI_GYM\testAgent.py``` got this error:
```
$ python testAgent.py
[2019-05-18 17:33:31,369] Making new env: gvgai-testgame1-lvl0-v0
/home/islab/rozen_proj/mlsh/gym/gym/envs/registration.py:17: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False)
Connecting to host 127.0.0.1 at port 48203 ...
Client connected to server [OK]
Traceback (most recent call last):
  File "testAgent.py", line 13, in <module>
    env = gym_gvgai.make(game + '-' + level)
  File "/home/islab/rozen_proj/mlsh/gym/gym/envs/registration.py", line 161, in make
    return registry.make(id)
  File "/home/islab/rozen_proj/mlsh/gym/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/home/islab/rozen_proj/mlsh/gym/gym/envs/registration.py", line 86, in make
    env = cls(**self._kwargs)
  File "/home/islab/rozen_proj/GVGAI_GYM/gym_gvgai/envs/gvgai_env.py", line 45, in __init__
    self.observation_space = spaces.Box(low=0, high=255, shape=self.img.shape, dtype=np.uint8)
TypeError: __init__() got an unexpected keyword argument 'dtype'
```
I have already installed ```GVGAI_GYM``` and ```gym```:
```
gym                                0.11.0     /home/islab/anaconda3/lib/python3.6/site-packages
gym-gvgai                          0.0.3      /home/islab/rozen_proj/GVGAI_GYM
```

my python version is ```anaconda python3.6.8``` and operation system is ```ubuntu16.04``` how should I solve this problem?

**Comment by pbontrager** [comment]
Never saw this before. Maybe gym should be reinstalled? Did you get this resolved?
