### ISSUE TITLE
Installation Issue: invalid literal for int() with base 10: 'vl1.txt'

### ISSUE THREAD

**Issue by makdoudN** [rubenrtorrado/GVGAI_GYM#7]
Hi, 
Thank for your hard work providing those cool environments :)

Unfortunately, I can't install GVGAI_GYM.
Do you have some clues on what is missing?

Here some traces of the installation and the error message:

Obtaining file:///home/nizam/Documents/GVGAI_GYM
Requirement already satisfied: gym>=0.10.5 in /home/nizam/anaconda3/envs/torch-master/lib/python3.6/site-packages (from gym-gvgai==0.0.3) (0.10.5)
Requirement already satisfied: numpy>=1.13.3 in /home/nizam/anaconda3/envs/torch-master/lib/python3.6/site-packages (from gym-gvgai==0.0.3) (1.14.5)
Requirement already satisfied: requests>=2.0 in /home/nizam/anaconda3/envs/torch-master/lib/python3.6/site-packages (from gym>=0.10.5->gym-gvgai==0.0.3) (2.19.1)
Requirement already satisfied: pyglet>=1.2.0 in /home/nizam/anaconda3/envs/torch-master/lib/python3.6/site-packages (from gym>=0.10.5->gym-gvgai==0.0.3) (1.3.2)
Requirement already satisfied: six in /home/nizam/anaconda3/envs/torch-master/lib/python3.6/site-packages (from gym>=0.10.5->gym-gvgai==0.0.3) (1.11.0)
Requirement already satisfied: urllib3<1.24,>=1.21.1 in /home/nizam/anaconda3/envs/torch-master/lib/python3.6/site-packages (from requests>=2.0->gym>=0.10.5->gym-gvgai==0.0.3) (1.23)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/nizam/anaconda3/envs/torch-master/lib/python3.6/site-packages (from requests>=2.0->gym>=0.10.5->gym-gvgai==0.0.3) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /home/nizam/anaconda3/envs/torch-master/lib/python3.6/site-packages (from requests>=2.0->gym>=0.10.5->gym-gvgai==0.0.3) (2018.4.16)
Requirement already satisfied: idna<2.8,>=2.5 in /home/nizam/anaconda3/envs/torch-master/lib/python3.6/site-packages (from requests>=2.0->gym>=0.10.5->gym-gvgai==0.0.3) (2.7)
Requirement already satisfied: future in /home/nizam/anaconda3/envs/torch-master/lib/python3.6/site-packages (from pyglet>=1.2.0->gym>=0.10.5->gym-gvgai==0.0.3) (0.16.0)
Installing collected packages: gym-gvgai
  Found existing installation: gym-gvgai 0.0.3
    Uninstalling gym-gvgai-0.0.3:
      Successfully uninstalled gym-gvgai-0.0.3
  Running setup.py develop for gym-gvgai
Successfully installed gym-gvgai

Python 3.6.6 |Anaconda custom (64-bit)| (default, Jun 28 2018, 17:14:51) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gym
>>> import gym_gvgai
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nizam/Documents/GVGAI_GYM/gym_gvgai/__init__.py", line 15, in <module>
    version = int(game.split('_')[1][1:])
ValueError: invalid literal for int() with base 10: 'vl1.txt'

I am on Ubuntu 16.04, use python3.6.6 (anaconda) and latest version of gym.

**Comment by makdoudN** [comment]
It works well, thank you.
